
title: Matthias' Blog
email: matthias.brown@etu.univ-tours.fr
description: >-
  Hey ! I'm Matthias, a passionate computer science student. 
  If you're eager to learn about Programming, Computer Security and much more, read my stories.
  So, this is what I learned today...
url: "https://mabocode.github.io" # the base hostname & protocol for your site, e.g. http://example.com
base_url: "/"
show_excerpts: true

#paginate: 6
#paginate_path: "/blog-v2/page:num/"

highlighter: rouge

# My info
my_info:
  full_name     : Matthias Brown
  pseudo        : MbM
  profession    : Computer Science Student
  email         : matthias.brown@etu.univ-tours.fr
  socials:
    github      : MaBoCode
    linkedIn    : matthias-brown-2ba617173

  
sass:
  sass_dir: _sass
  style: compressed

# Serving
detach              : false
#port                : 4004
#host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false
livereload          : true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Filtering Content
show_drafts         : null
limit_posts         : 20
future              : false
unpublished         : false

incremental         : true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /posts/:categories/:year/:month/:day/:title